version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deployment/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: backend/RunBackendScript.sh
      timeout: 300
      runas: ec2-user
    - location: Frontend/RunFrontendScript.sh
      timeout: 300
      runas: ec2-user
  #ApplicationStop:
    #- location: scripts/stop_server
      #timeout: 300
      #runas: root