export const GET_CATEGORIES_WRITERS_INIT = "GET_CATEGORIES_WRITERS_INIT";
export const GET_CATEGORIES_WRITERS_SUCCESS = "GET_CATEGORIES_WRITER_SUCCESS";
export const GET_CATEGORIES_WRITERS_FAILURE = "GET_CATEGORIES_WRITERS_FAILURE";

export const GET_STATUS_INIT = "GET_STATUS_INIT";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_FAILURE = "GET_STATUS_FAILURE";

export const ADD_WRITER = "ADD_WRITER";
export const REMOVE_WRITER = "REMOVE_WRITER";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

export const SEND_SELECTED_INIT = "SEND_SELECTED_INIT";
export const SEND_SELECTED_SUCCESS = "SEND_SELECTED_SUCCESS";
export const SEND_SELECTED_FAILURE = "SEND_SELECTED_FAILURE";

export const SEND_PROFILE_INFO_INIT = "SEND_PROFILE_INFO_INIT";
export const SEND_PROFILE_INFO_SUCCESS = "SEND_PROFILE_INFO_SUCCESS";
export const SEND_PROFILE_INFO_FAILURE = "SEND_PR0FILE_INFO_FAILURE";

export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CHECK_USERNAME_INIT = "CHECK_USERNAME_INIT";
export const CHECK_USERNAME_SUCCESS = "CHECK_USERNAME_SUCCESS";
export const CHECK_USERNAME_FAILURE = "CHECK_USERNAME_FAILURE";

export const GET_OTP_INIT = "GET_OTP_INIT";
export const GET_OTP_SUCCESS = "GET_OTP_SUCCESS";
export const GET_OTP_FAILURE = "GET_OTP_FAILURE";

export const VERIFY_OTP_INIT = "VERIFY_OTP_INIT";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const GET_EMAIL_OTP_INIT = "GET_EMAIL_OTP_INIT";
export const GET_EMAIL_OTP_SUCCESS = "GET_EMAIL_OTP_SUCCESS";
export const GET_EMAIL_OTP_FAILURE = "GET_EMAIL_OTP_FAILURE";

export const VERIFY_EMAIL_OTP_INIT = "VERIFY_EMAIL_OTP_INIT";
export const VERIFY_EMAIL_OTP_SUCCESS = "VERIFY_EMAIL_OTP_SUCCESS";
export const VERIFY_EMAIL_OTP_FAILURE = "VERIFY_EMAIL_OTP_FAILURE";

export const FORGOT_GET_OTP_INIT = "FORGOT_GET_OTP_INIT";
export const FORGOT_GET_OTP_SUCCESS = "FORGOT_GET_OTP_SUCCESS";
export const FORGOT_GET_OTP_FAILURE = "FORGOT_GET_OTP_FAILURE";

export const FORGOT_VERIFY_OTP_INIT = "FORGOT_VERIFY_OTP_INIT";
export const FORGOT_VERIFY_OTP_SUCCESS = "FORGOT_VERIFY_OTP_SUCCESS";
export const FORGOT_VERIFY_OTP_FAILURE = "FORGOT_VERIFY_OTP_FAILURE";

export const FORGOT_GET_EMAIL_OTP_INIT = "FORGOT_GET_EMAIL_OTP_INIT";
export const FORGOT_GET_EMAIL_OTP_SUCCESS = "FORGOT_GET_EMAIL_OTP_SUCCESS";
export const FORGOT_GET_EMAIL_OTP_FAILURE = "FORGOT_GET_EMAIL_OTP_FAILURE";

export const FORGOT_VERIFY_EMAIL_OTP_INIT = "FORGOT_VERIFY_EMAIL_OTP_INIT";
export const FORGOT_VERIFY_EMAIL_OTP_SUCCESS =
  "FORGOT_VERIFY_EMAIL_OTP_SUCCESS";
export const FORGOT_VERIFY_EMAIL_OTP_FAILURE =
  "FORGOT_VERIFY_EMAIL_OTP_FAILURE";

export const USER_PHONE = "USER_PHONE";
export const USER_EMAIL = "USER_EMAIL";
export const USER_NAME = "USER_NAME";
export const USER_PASSWORD = "USER_PASSWORD";
export const USER_USERNAME = "USER_USERNAME";

export const RESET_PASSWORD_INIT = "RESET_PASSWORD_INIT";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
export const RESET_PASSWORD_STATE = "RESET_PASSWORD_STATE";

export const LOGOUT_INIT = "LOGOUT_INIT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const GET_REFRESH_TOKEN_INIT = "GET_REFRESH_TOKEN_INIT";
export const GET_REFRESH_TOKEN_SUCCESS = "GET_REFRESH_TOKEN_SUCCESS";
export const GET_REFRESH_TOKEN_FAILURE = "GET_REFRESH_TOKEN_FAILURE";

export const UPLOAD_IMAGE_INIT = "UPLOAD_IMAGE_INIT";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";

export const GET_UNSPLASH_INIT = "GET_UNSPLASH_INIT";
export const GET_UNSPLASH_SUCCESS = "GET_UNSPLASH_SUCCESS";
export const GET_UNSPLASH_FAILURE = "GET_UNSPLASH_FAILURE";

export const GET_NFT_INIT = "GET_NFT_INIT";
export const GET_NFT_SUCCESS = "GET_NFT_SUCCESS";
export const GET_NFT_FAILURE = "GET_NFT_FAILURE";

export const CREATE_NEW_ARTICLE_INIT = "CREATE_NEW_ARTICLE_INIT";
export const CREATE_NEW_ARTICLE_SUCCESS = "CREATE_NEW_ARTICLE_SUCCESS";
export const CREATE_NEW_ARTICLE_FAILURE = "CREATE_NEW_ARTICLE_FAILURE";

export const UPLOAD_ARTICLE_INIT = "UPLOAD_ARTICLE_INIT";
export const UPLOAD_ARTICLE_SUCCESS = "UPLOAD_ARTICLE_SUCCESS";
export const UPLOAD_ARTICLE_FAILURE = "UPLOAD_ARTICLE_FAILURE";

export const GET_ARTICLE_INIT = "GET_ARTICLE_INIT";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAILURE = "GET_ARTICLE_FAILURE";

export const GET_ALL_ARTICLES_INIT = "GET_ALL_ARTICLES_INIT";
export const GET_ALL_ARTICLES_SUCCESS = "GET_ALL_ARTICLES_SUCCESS";
export const GET_ALL_ARTICLES_FAILURE = "GET_ALL_ARTICLES_FAILURE";

export const GET_FOLLOWED_WRITERS_INIT = "GET_FOLLOWED_WRITERS_INIT";
export const GET_FOLLOWED_WRITERS_SUCCESS = "GET_FOLLOWED_WRITERS_SUCCESS";
export const GET_FOLLOWED_WRITERS_FAILURE = "GET_FOLLOWED_WRITERS_FAILURE";

export const BOOKMARK_ARTICLE_INIT = "BOOKMARK_ARTICLE_INIT";
export const BOOKMARK_ARTICLE_SUCCESS = "BOOKMARK_ARTICLE_SUCCESS";
export const BOOKMARK_ARTICLE_FAILURE = "BOOKMARK_ARTICLE_FAILURE";

export const DISCARD_ARTICLE_INIT = "DISCARD_ARTICLE_INIT";
export const DISCARD_ARTICLE_SUCCESS = "DISCARD_ARTICLE_SUCCESS";
export const DISCARD_ARTICLE_FAILURE = "DISCARD_ARTICLE_FAILURE";

export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";

export const GET_PUBLICATIONS_INIT = "GET_PUBLICATIONS_INIT";
export const GET_PUBLICATIONS_SUCCESS = "GET_PUBLICATIONS_SUCCESS";
export const GET_PUBLICATIONS_FAILURE = "GET_PUBLICATIONS_FAILURE";

export const CREATE_PUBLICATIONS_INIT = "CREATE_PUBLICATIONS_INIT";
export const CREATE_PUBLICATIONS_SUCCESS = "CREATE_PUBLICATIONS_SUCCESS";
export const CREATE_PUBLICATIONS_FAILURE = "CREATE_PUBLICATIONS_FAILURE";

export const CREATE_ABOUT_PUBLICATION_INIT = "CREATE_ABOUT_PUBLICATION_INIT";
export const CREATE_ABOUT_PUBLICATION_SUCCESS =
  "CREATE_ABOUT_PUBLICATION_SUCCESS";
export const CREATE_ABOUT_PUBLICATION_FAILURE =
  "CREATE_ABOUT_PUBLICATION_FAILURE";

export const UPDATE_PUBLICATIONS_INIT = "UPDATE_PUBLICATIONS_INIT";
export const UPDATE_PUBLICATIONS_SUCCESS = "UPDATE_PUBLICATIONS_SUCCESS";
export const UPDATE_PUBLICATIONS_FAILURE = "UPDATE_PUBLICATIONS_FAILURE";

export const DELETE_PUBLICATION = "DELETE_PUBLICATION";
export const DELETE_PUBLICATION_SUCCESS = "DELETE_PUBLICATION_SUCCESS";

export const GET_ABOUT_PUBLICATION_INIT = "GET_ABOUT_PUBLICATIONS_INIT";
export const GET_ABOUT_PUBLICATION_SUCCESS = "GET_ABOUT_PUBLICATIONS_SUCCESS";
export const GET_ABOUT_PUBLICATION_FAILURE = "GET_ABOUT_PUBLICATIONS_FAILURE";

// articles related Actions:
export const GET_ARTICLES_INIT = "GET_ARTICLES_INIT";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAILURE = "GET_ARTICLES_FAILURE";

export const DELETE_ARTICLE_INIT = "DELETE_ARTICLE_INIT";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAILURE = "DELETE_ARTICLE_FAILURE";

export const GET_STORY_INIT = "GET_STORY_INIT";
export const GET_STORY_SUCCESS = "GET_STORY_SUCCESS";
export const GET_STORY_FAILURE = "GET_STORY_FAILURE";

export const GET_MORE_FROM_WRITER_INIT = "GET_MORE_FROM_WRITER_INIT";
export const GET_MORE_FROM_WRITER_SUCCESS = "GET_MORE_FROM_WRITER_SUCCESS";
export const GET_MORE_FROM_WRITER_FAILURE = "GET_MORE_FROM_WRITER_FAILURE";

export const GET_PICK_FAV_DATA_INIT = "GET_PICK_FAV_DATA_INIT";
export const GET_PICK_FAV_DATA_SUCCESS = "GET_PICK_FAV_DATA_SUCCESS";
export const GET_PICK_FAV_DATA_FAILURE = "GET_PICK_FAV_DATA_FAILURE";

export const FOLLOW_WRITER_INIT = "FOLLOW_WRITER_INIT";
export const FOLLOW_WRITER_SUCCESS = "FOLLOW_WRITER_SUCCESS";
export const FOLLOW_WRITER_FAILURE = "FOLLOW_WRITER_FAILURE";

export const FOLLOW_MULTIPLE_WRITERS_INIT = "FOLLOW_MULTIPLE_WRITERS_INIT";
export const FOLLOW_MULTIPLE_WRITERS_SUCCESS =
  "FOLLOW_MULTIPLE_WRITERS_SUCCESS";
export const FOLLOW_MULTIPLE_WRITERS_FAILURE =
  "FOLLOW_MULTIPLE_WRITERS_FAILURE";

export const GOOGLE_SIGN_UP_INIT = "GOOGLE_SIGN_UP_INIT";
export const GOOGLE_SIGN_UP_SUCCESS = "GOOGLE_SIGN_UP_SUCCESS";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_UP_FAILURE = "GOOGLE_SIGN_UP_FAILURE";

export const GET_HOME_PAGE_DATA_INIT = "GET_HOME_PAGE_DATA_INIT";
export const GET_HOME_PAGE_DATA_SUCCESS = "GET_HOME_PAGE_DATA_SUCCESS";
export const GET_HOME_PAGE_DATA_FAILURE = "GET_HOME_PAGE_DATA_FAILURE";

export const SUBMIT_INIT = "SUBMIT_INIT";
export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";
export const SUBMIT_FAILURE = "SUBMIT_FAILURE";

export const WALLET_SEND_OTP_INIT = "WALLET_SEND_OTP_INIT";
export const WALLET_SEND_OTP_SUCCESS = "WALLET_SEND_OTP_SUCCESS";
export const WALLET_SEND_OTP_FAILURE = "WALLET_SEND_OTP_FAILURE";

export const WALLET_ACTIVATE_INIT = "WALLET_ACTIVATE_INIT";
export const WALLET_ACTIVATE_SUCCESS = "WALLET_ACTIVATE_SUCCESS";
export const WALLET_ACTIVATE_FAILURE = "WALLET_SEND_ACTIVATE_FAILURE";

export const GET_ARTICLES_FOR_PUBLICATION_INIT =
  "GET_ARTICLES_FOR_PUBLICATION_INIT";
export const GET_ARTICLES_FOR_PUBLICATION_SUCCESS =
  "GET_ARTICLES_FOR_PUBLICATION_SUCCESS";
export const GET_ARTICLES_FOR_PUBLICATION_FAILURE =
  "GET_ARTICLES_FOR_PUBLICATION_FAILURE";

export const GET_LATEST_ARTICLES_FOR_WRITER_INIT =
  "GET_LATEST_ARTICLES_FOR_WRITER_INIT";
export const GET_LATEST_ARTICLES_FOR_WRITER_SUCCESS =
  "GET_LATEST_ARTICLES_FOR_WRITER_SUCCESS";
export const GET_LATEST_ARTICLES_FOR_WRITER_FAILURE =
  "GET_LATEST_ARTICLES_FOR_WRITER_FAILURE";

export const HOMEPAGE_SET_ACTIVE_INDEX_DATA = "HOMEPAGE_SET_ACTIVE_INDEX_DATA";
